name: CI

on:
  pull_request:
  push:
      branches:
      - main

jobs:
  run-tests:
    runs-on: [ubuntu-latest]

    env:
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up python3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Run tests
      run: |
        pip install pytest-cov django
        pytest --cov=./ --cov-report=xml

    - name: Report test coverage to DeepSource
      uses: deepsourcelabs/test-coverage-action@master
      with:
        key: python
        coverage-file: coverage.xml
        dsn: ${{ secrets.DEEPSOURCE_DSN }}
        fail-ci-on-error: true
